/*
 * Javalin - https://javalin.io
 * Copyright 2017 David Åse
 * Licensed under Apache 2.0: https://github.com/tipsy/javalin/blob/master/LICENSE
 */

package io.javalin;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import io.javalin.core.util.Header;
import org.junit.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.isEmptyOrNullString;

public class TestEtags {

    @Test
    public void test_automatic_etags_work_get() throws Exception {
        Javalin app = Javalin.create().enableAutogeneratedEtags().start(0);
        app.get("/automatic", ctx -> ctx.result("Hello!"));
        HttpResponse<String> response = Unirest.get("http://localhost:" + app.port() + "/automatic").asString();
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("Hello!"));
        String etag = response.getHeaders().getFirst(Header.ETAG);
        HttpResponse<String> response2 = Unirest.get("http://localhost:" + app.port() + "/automatic").header(Header.IF_NONE_MATCH, etag).asString();
        String etag2 = response2.getHeaders().getFirst(Header.ETAG);
        assertThat(response2.getStatus(), is(304));
        assertThat(response2.getBody(), isEmptyOrNullString());
        assertThat(etag, is(etag2));
        app.stop();
    }

    @Test
    public void test_automatic_etags_work_put() throws Exception {
        Javalin app = Javalin.create().enableAutogeneratedEtags().start(0);
        app.put("/automatic", ctx -> ctx.result("Hello!"));
        HttpResponse<String> response = Unirest.put("http://localhost:" + app.port() + "/automatic").asString();
        assertThat(response.getHeaders().getFirst(Header.ETAG), isEmptyOrNullString());
        app.stop();
    }

    @Test
    public void test_manual_etags_are_preferred() throws Exception {
        Javalin app = Javalin.create().enableAutogeneratedEtags().start(0);
        app.get("/manual", ctx -> ctx.result("Hello!").header(Header.ETAG, "1234"));
        HttpResponse<String> response = Unirest.get("http://localhost:" + app.port() + "/manual").asString();
        assertThat(response.getStatus(), is(200));
        assertThat(response.getBody(), is("Hello!"));
        String etag = response.getHeaders().getFirst(Header.ETAG);
        HttpResponse<String> response2 = Unirest.get("http://localhost:" + app.port() + "/manual").header(Header.IF_NONE_MATCH, etag).asString();
        assertThat(response2.getStatus(), is(304));
        assertThat(response2.getBody(), isEmptyOrNullString());
        assertThat(etag, is("1234"));
        app.stop();
    }

    @Test
    public void test_manual_etags_work_put() throws Exception {
        Javalin app = Javalin.create().start(0);
        app.put("/manual", ctx -> ctx.result("Hello!").header(Header.ETAG, "1234"));
        HttpResponse<String> response = Unirest.put("http://localhost:" + app.port() + "/manual").asString();
        assertThat(response.getHeaders().getFirst(Header.ETAG), is("1234"));
        app.stop();
    }

    @Test
    public void test_no_etags_work() throws Exception {
        Javalin app = Javalin.create().start(0);
        app.get("/", ctx -> ctx.result("Hello!"));
        assertThat(Unirest.get("http://localhost:" + app.port() + "/").asString().getBody(), is("Hello!"));
        assertThat(Unirest.get("http://localhost:" + app.port() + "/").asString().getStatus(), is(200));
        assertThat(Unirest.get("http://localhost:" + app.port() + "/").asString().getHeaders().getFirst(Header.ETAG), isEmptyOrNullString());
        app.stop();
    }

}
