package io.javalin.core.util

import io.javalin.plugin.openapi.handler.functional.SerializableFunction
import java.lang.invoke.SerializedLambda
import java.lang.reflect.Field
import java.lang.reflect.Method

internal val Any.kotlinFieldName // this is most likely a very stupid solution
    get() = this.javaClass.toString().removePrefix(this.parentClass.toString() + "$").takeWhile { it != '$' }

internal val Any.javaFieldName: String?
    get() = try {
        parentClass.declaredFields.find { it.isAccessible = true; it.get(it) == this }?.name
    } catch (ignored: Exception) { // Nothing really matters.
        null
    }

internal val Any.methodName: String? // broken in jdk9+ since ConstantPool has been removed
    get() {
//        val constantPool = Class::class.java.getDeclaredMethod("getConstantPool").apply { isAccessible = true }.invoke(javaClass) as ConstantPool
//        for (i in constantPool.size downTo 0) {
//            try {
//                val name = constantPool.getMemberRefInfoAt(i)[1]
//                // Autogenerated ($), constructor, or kotlin's check (fix maybe?)
//                if (name.contains("(\\$|<init>|checkParameterIsNotNull)".toRegex())) {
//                    continue
//                } else {
//                    return name
//                }
//            } catch (ignored: Exception) {
//            }
//        }
        return null
    }
internal val Any.parentClass: Class<*> get() = Class.forName(this.javaClass.name.takeWhile { it != '$' })

internal val Any.implementingClassName: String? get() = this.javaClass.name

internal val Any.isClass: Boolean get() = this is Class<*>

internal val Any.isKotlinAnonymousLambda: Boolean get() = this.javaClass.enclosingMethod != null

internal val Any.isKotlinMethodReference: Boolean get() = this.javaClass.declaredFields.any { it.name == "function" }

internal val Any.isKotlinField: Boolean get() = this.javaClass.fields.any { it.name == "INSTANCE" }

internal val Any.isJavaAnonymousLambda: Boolean get() = this.javaClass.isSynthetic

internal val Any.hasMethodName: Boolean get() = methodName != null

internal val Any.isJavaNonStaticMethodReference: Boolean get() = javaClass.declaredMethods.any { it.name == methodReferenceReflectionMethodName }

internal val Any.isJavaField: Boolean get() = this.javaFieldName != null

internal fun Any.runMethod(name: String): Any = this.javaClass.getMethod(name).apply { isAccessible = true }.invoke(this)

internal val Any.lambdaField: Field?
    get() = when {
        isKotlinField -> parentClass.getDeclaredFieldByName(kotlinFieldName)
        isJavaField -> parentClass.getDeclaredFieldByName(javaFieldName!!)
        else -> null
    }

internal fun Any.getFieldValue(fieldName: String): Any {
    val field = this::class.java.getDeclaredField(fieldName)
    field.isAccessible = true
    return field.get(this)
}

internal fun Class<*>.getMethodByName(methodName: String): Method? {
    val isName = { method: Method -> method.name == methodName }
    return declaredMethods.find(isName) ?: methods.find(isName)
}

internal fun Class<*>.getMethodByNameAndSignature(methodName: String, signature: String): Method? {
    val isName = { method: Method -> method.name == methodName && method.signature == signature }
    return declaredMethods.find(isName) ?: methods.find(isName)
}

internal val Method.signature: String get() {
    val result = StringBuilder()
    result.append('(')
    parameterTypes.forEach { result.append(it.signature).append(';') }
    result.append(')')
    result.append(returnType.signature)
    return result.toString()
}

internal val Class<*>.signature: String get() = when {
        this == Boolean::class.java -> "Z"
        this == Byte::class.java -> "B"
        this == Char::class.java -> "C"
        this == Boolean::class.java -> "D"
        this == Float::class.java -> "F"
        this == Int::class.java -> "I"
        this == Short::class.java -> "S"
        this == Void.TYPE -> "V"
        this == Array<Any>::class.java -> "[${this.componentType.signature}"
        else -> "L${this.name.replace(".", "/")}"
    }

internal fun SerializableFunction.getReferencedMethodNameAndSignature(): Pair<String, String>? {
    val serializedLambda = this::class.java.getMethodByNameAndSignature("writeReplace", "()Ljava/lang/Object").apply {
        this@apply?.isAccessible = true
    }?.invoke(this) as SerializedLambda?

    return serializedLambda?.let { it.implMethodName to it.implMethodSignature }
}

internal fun Class<*>.getDeclaredFieldByName(methodName: String): Field? = declaredFields
        .find { it.name == methodName }

internal val Class<*>.methodsNotDeclaredByObject
    get(): Array<Method> = (declaredMethods + methods)
            .toSet()
            .filter { it.declaringClass != Object::class.java }
            .toTypedArray()



internal const val methodReferenceReflectionMethodName = "get\$Lambda"
internal const val parentFieldReflectionMethodName = "arg\$1"
