/*
 * Javalin - https://javalin.io
 * Copyright 2017 David Åse
 * Licensed under Apache 2.0: https://github.com/tipsy/javalin/blob/master/LICENSE
 */

package io.javalin.http

object Header {
    // Standard HTTP headers (RFC 7231, 7232, 7233, 7234, 7235, 9110)
    const val ACCEPT = "Accept"
    const val ACCEPT_CHARSET = "Accept-Charset"
    const val ACCEPT_ENCODING = "Accept-Encoding"
    const val ACCEPT_LANGUAGE = "Accept-Language"
    const val ACCEPT_PATCH = "Accept-Patch"
    const val ACCEPT_POST = "Accept-Post"
    const val ACCEPT_RANGES = "Accept-Ranges"
    const val ACCESS_CONTROL_ALLOW_CREDENTIALS = "Access-Control-Allow-Credentials"
    const val ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers"
    const val ACCESS_CONTROL_ALLOW_METHODS = "Access-Control-Allow-Methods"
    const val ACCESS_CONTROL_ALLOW_ORIGIN = "Access-Control-Allow-Origin"
    const val ACCESS_CONTROL_EXPOSE_HEADERS = "Access-Control-Expose-Headers"
    const val ACCESS_CONTROL_MAX_AGE = "Access-Control-Max-Age"
    const val ACCESS_CONTROL_REQUEST_HEADERS = "Access-Control-Request-Headers"
    const val ACCESS_CONTROL_REQUEST_METHOD = "Access-Control-Request-Method"
    const val AGE = "Age"
    const val ALLOW = "Allow"
    const val ALT_SVC = "Alt-Svc"
    const val AUTHORIZATION = "Authorization"
    const val CACHE_CONTROL = "Cache-Control"
    const val CLEAR_SITE_DATA = "Clear-Site-Data"
    const val CONNECTION = "Connection"
    const val CONTENT_ENCODING = "Content-Encoding"
    const val CONTENT_DISPOSITION = "Content-Disposition"
    const val CONTENT_LANGUAGE = "Content-Language"
    const val CONTENT_LENGTH = "Content-Length"
    const val CONTENT_LOCATION = "Content-Location"
    const val CONTENT_RANGE = "Content-Range"
    const val CONTENT_SECURITY_POLICY = "Content-Security-Policy"
    const val CONTENT_SECURITY_POLICY_REPORT_ONLY = "Content-Security-Policy-Report-Only"
    const val CONTENT_TYPE = "Content-Type"
    const val COOKIE = "Cookie"
    const val CROSS_ORIGIN_EMBEDDER_POLICY = "Cross-Origin-Embedder-Policy"
    const val CROSS_ORIGIN_OPENER_POLICY = "Cross-Origin-Opener-Policy"
    const val CROSS_ORIGIN_RESOURCE_POLICY = "Cross-Origin-Resource-Policy"
    const val DATE = "Date"
    const val DNT = "DNT"
    const val EARLY_DATA = "Early-Data"
    const val ETAG = "ETag"
    const val EXPECT = "Expect"
    const val EXPECT_CT = "Expect-CT"
    const val EXPIRES = "Expires"
    const val FORWARDED = "Forwarded"
    const val FROM = "From"
    const val HOST = "Host"
    const val IF_MATCH = "If-Match"
    const val IF_MODIFIED_SINCE = "If-Modified-Since"
    const val IF_NONE_MATCH = "If-None-Match"
    const val IF_RANGE = "If-Range"
    const val IF_UNMODIFIED_SINCE = "If-Unmodified-Since"
    const val KEEP_ALIVE = "Keep-Alive"
    const val LAST_MODIFIED = "Last-Modified"
    const val LINK = "Link"
    const val LOCATION = "Location"
    const val MAX_FORWARDS = "Max-Forwards"
    const val NEL = "NEL"
    const val ORIGIN = "Origin"
    const val PERMISSIONS_POLICY = "Permissions-Policy"
    const val PRAGMA = "Pragma"
    const val PREFER = "Prefer"
    const val PREFERENCE_APPLIED = "Preference-Applied"
    const val PRIORITY = "Priority"
    const val PROXY_AUTHENTICATE = "Proxy-Authenticate"
    const val PROXY_AUTHORIZATION = "Proxy-Authorization"
    const val RANGE = "Range"
    const val REFERER = "Referer"
    const val REFERRER_POLICY = "Referrer-Policy"
    const val RETRY_AFTER = "Retry-After"
    const val SEC_FETCH_DEST = "Sec-Fetch-Dest"
    const val SEC_FETCH_MODE = "Sec-Fetch-Mode"
    const val SEC_FETCH_SITE = "Sec-Fetch-Site"
    const val SEC_FETCH_USER = "Sec-Fetch-User"
    const val SEC_PURPOSE = "Sec-Purpose"
    const val SEC_WEBSOCKET_ACCEPT = "Sec-WebSocket-Accept"
    const val SEC_WEBSOCKET_EXTENSIONS = "Sec-WebSocket-Extensions"
    const val SEC_WEBSOCKET_KEY = "Sec-WebSocket-Key"
    const val SEC_WEBSOCKET_PROTOCOL = "Sec-WebSocket-Protocol"
    const val SEC_WEBSOCKET_VERSION = "Sec-WebSocket-Version"
    const val SERVER = "Server"
    const val SERVER_TIMING = "Server-Timing"
    const val SERVICE_WORKER_NAVIGATION_PRELOAD = "Service-Worker-Navigation-Preload"
    const val SET_COOKIE = "Set-Cookie"
    const val SOURCEMAP = "SourceMap"
    const val STRICT_TRANSPORT_SECURITY = "Strict-Transport-Security"
    const val TE = "TE"
    const val TIMING_ALLOW_ORIGIN = "Timing-Allow-Origin"
    const val TRAILER = "Trailer"
    const val TRANSFER_ENCODING = "Transfer-Encoding"
    const val UPGRADE = "Upgrade"
    const val UPGRADE_INSECURE_REQUESTS = "Upgrade-Insecure-Requests"
    const val USER_AGENT = "User-Agent"
    const val VARY = "Vary"
    const val VIA = "Via"
    const val WARNING = "Warning"
    const val WWW_AUTHENTICATE = "WWW-Authenticate"

    // Proxy, load balancer, and CDN headers
    const val FORWARDED_HOST = "X-Forwarded-Host"
    const val FORWARDED_PORT = "X-Forwarded-Port"
    const val FORWARDED_SERVER = "X-Forwarded-Server"
    const val X_CORRELATION_ID = "X-Correlation-ID"
    const val X_FORWARDED_FOR = "X-Forwarded-For"
    const val X_FORWARDED_PROTO = "X-Forwarded-Proto"
    const val X_REAL_IP = "X-Real-IP"
    const val X_REQUEST_ID = "X-Request-ID"

    // Security headers
    const val X_CONTENT_TYPE_OPTIONS = "X-Content-Type-Options"
    const val X_DNS_PREFETCH_CONTROL = "X-DNS-Prefetch-Control"
    const val X_DOWNLOAD_OPTIONS = "X-Download-Options"
    const val X_FRAME_OPTIONS = "X-Frame-Options"
    const val X_PERMITTED_CROSS_DOMAIN_POLICIES = "X-Permitted-Cross-Domain-Policies"
    const val X_POWERED_BY = "X-Powered-By"
    const val X_XSS_PROTECTION = "X-XSS-Protection"

    // Common non-standard headers
    const val X_ACCEL_BUFFERING = "X-Accel-Buffering"
    const val X_ACCEL_REDIRECT = "X-Accel-Redirect"
    const val X_HTTP_METHOD_OVERRIDE = "X-HTTP-Method-Override"
    const val X_RATELIMIT_LIMIT = "X-RateLimit-Limit"
    const val X_RATELIMIT_REMAINING = "X-RateLimit-Remaining"
    const val X_RATELIMIT_RESET = "X-RateLimit-Reset"

    // AWS / Cloud load balancer headers
    const val X_AMZN_TRACE_ID = "X-Amzn-Trace-Id"

    // Cloudflare headers
    const val CF_CONNECTING_IP = "CF-Connecting-IP"
    const val CF_IPCOUNTRY = "CF-IPCountry"
    const val CF_RAY = "CF-RAY"

    // Akamai / Fastly / other CDN headers
    const val TRUE_CLIENT_IP = "True-Client-IP"
    const val X_CACHE = "X-Cache"
    const val X_CACHE_HITS = "X-Cache-Hits"
}
