package io.javalin

import io.javalin.core.JavalinServlet

class EmbeddedJavalin : Javalin() {

    override fun createServlet() = JavalinServlet(
        this,
        pathMatcher,
        exceptionMapper,
        errorMapper,
        debugLogging,
        requestLogger,
        dynamicGzipEnabled,
        autogeneratedEtagsEnabled,
        defaultContentType,
        maxRequestCacheBodySize,
        prefer405over404,
        singlePageHandler,
        null
    )

    @Deprecated("not available in standalone mode", level = DeprecationLevel.ERROR)
    override fun enableStaticFiles(classpathPath: String) = notAvailable("enableStaticFiles()")
    @Deprecated("not available in standalone mode", level = DeprecationLevel.ERROR)
    override fun contextPath(contextPath: String) = notAvailable("contextPath()")
    @Deprecated("not available in standalone mode", level = DeprecationLevel.ERROR)
    override fun start() = notAvailable("start()")
    private fun notAvailable(action: String): Nothing = throw RuntimeException("$action is not available in standalone mode")
}
