name: Run tests on Ubuntu manually

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8, 11]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw package --file pom.xml --batch-mode -X
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
